### ISSUE TITLE
iphone 15 pro support 

### ISSUE THREAD

**Issue by amrgetment** [StorybookToolkit/device_frame_plus#1]
could you add iphone 15 pro
here is chatgpt code

```
final info = DeviceInfo(
  identifier: const DeviceIdentifier(
    TargetPlatform.iOS,
    DeviceType.phone,
    'iphone-15-pro',
  ),
  name: 'iPhone 15 Pro',
  pixelRatio: 3.0, // Assuming 3.0 as a typical pixel ratio for modern iPhones
  frameSize: const Size(1179.0, 2556.0), // Physical resolution in pixels
  screenSize: const Size(390.0, 844.0), // Logical resolution (points) for this device
  safeAreas: const EdgeInsets.only(
    left: 0.0,
    top: 44.0, // Top notch area height
    right: 0.0,
    bottom: 34.0, // Bottom safe area height for gesture bar
  ),
  rotatedSafeAreas: const EdgeInsets.only(
    left: 44.0, // Side safe area for landscape mode
    top: 0.0,
    right: 44.0,
    bottom: 21.0, // Bottom safe area height in landscape
  ),
  framePainter: const _FramePainter(),
  screenPath: _screenPath,
);

```

**Comment by amrgetment** [comment]
I tried to make it as a custom device info but    `_FramePainter()`, `_screenPath` is not exported for public import
I will have to fully copy it to use it
it could be public like

`IphoneFramePainter(),` `IPhoneScreenPath()`

**Comment by mjablecnik** [comment]
_FramePainter() and _screenPath are generated files.

You can see it here for example: https://github.com/StorybookToolkit/device_frame_plus/tree/master/lib/src/devices/ios/iphone_13

You can generate it manualy here: https://fluttershapemaker.com/ or try ChatGPT again.

[_FramePainter](https://github.com/StorybookToolkit/device_frame_plus/blob/master/lib/src/devices/ios/iphone_13/frame.g.dart) code is painting device frame and [_screenPath](https://github.com/StorybookToolkit/device_frame_plus/blob/master/lib/src/devices/ios/iphone_13/screen.g.dart) code is painting screen view.

**Comment by amrgetment** [comment]
thanks for sharing that
